<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-27T10:43:37Z" name="Default suite" finished-at="2020-05-27T10:46:27Z" duration-ms="169562">
    <groups>
    </groups>
    <test started-at="2020-05-27T10:43:37Z" name="Default test" finished-at="2020-05-27T10:46:27Z" duration-ms="169562">
      <class name="com.triotree.test.website.FrontOffice.DepositBillingTest">
        <test-method is-config="true" signature="beforeSuite(java.lang.String)[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:13:37Z" name="beforeSuite" finished-at="2020-05-27T16:13:37Z" duration-ms="233" status="PASS">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:13:37Z" name="beforeclass" finished-at="2020-05-27T16:13:37Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:13:37Z" name="setUp" finished-at="2020-05-27T16:13:43Z" duration-ms="6356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="frontOfficeWithAvailDepositAmountTest()[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:13:43Z" name="frontOfficeWithAvailDepositAmountTest" finished-at="2020-05-27T16:16:26Z" duration-ms="162797" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Total Amount in Cash isEqual to or Exceeds message is not showing up]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Total Amount in Cash isEqual to or Exceeds message is not showing up
	at org.testng.Assert.fail(Assert.java:94)
	at com.triotree.test.website.TTWebsiteBaseTest.assertTrue(TTWebsiteBaseTest.java:183)
	at com.triotree.test.website.FrontOffice.DepositBillingTest.frontOfficeWithAvailDepositAmountTest(DepositBillingTest.java:143)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontOfficeWithAvailDepositAmountTest -->
        <test-method is-config="true" signature="tearDownSession()[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:16:27Z" name="tearDownSession" finished-at="2020-05-27T16:16:27Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSession -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.triotree.test.website.FrontOffice.DepositBillingTest@f8908f6]" started-at="2020-05-27T16:16:27Z" name="afterSuite" finished-at="2020-05-27T16:16:27Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.triotree.test.website.FrontOffice.DepositBillingTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
